name: ci
on:
  pull_request:
  push:
    branches: [main]

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Succeed (no-op)
        run: echo "No project-wide CI here; governance uses validate-json + branch-protection"