name: Deploy Make blueprints

on:
  push:
    branches: [ main ]
    paths:
      - "make/blueprints/**/*.json"
  workflow_dispatch: {}   # allow manual runs from Actions tab

permissions:
  contents: read

jobs:
  import_blueprints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure jq is available
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Collect blueprint files
        id: files
        shell: bash
        run: |
          set -euo pipefail

          # Default to no files
          CHANGED=""

          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            # For pushes, diff against the previous commit if available
            BASE="${GITHUB_EVENT_BEFORE:-}"
            if [[ -z "${BASE}" || "${BASE}" == "0000000000000000000000000000000000000000" ]]; then
              # First push on branch (no before SHA) – take all tracked blueprints
              CHANGED=$(git ls-files 'make/blueprints/**/*.json' || true)
            else
              CHANGED=$(git diff --name-only "${BASE}" "${GITHUB_SHA}" \
                | grep -E '^make/blueprints/.*\.json$' || true)
            fi
          else
            # For manual runs, deploy everything we find
            CHANGED=$(find make/blueprints -type f -name '*.json' 2>/dev/null || true)
          fi

          echo "files<<EOF" >> "$GITHUB_OUTPUT"
          echo "${CHANGED}" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

          echo "Discovered files:"
          echo "${CHANGED}"

      - name: Import blueprints to Make
        if: steps.files.outputs.files != ''
        env:
          MAKE_API_TOKEN: ${{ secrets.MAKE_API_TOKEN }}
          MAKE_TEAM_ID:   ${{ secrets.MAKE_TEAM_ID }}
          MAKE_API_BASE:  ${{ secrets.MAKE_API_BASE }}   # optional; default used if unset
        shell: bash
        run: |
          set -euo pipefail
          # Default to EU2 tenant API. Change the default if your org is on a different region.
          API="${MAKE_API_BASE:-https://eu2.make.com/api/v2}"
          IMPORT_URL="${API}/blueprints/import"
          echo "Using Make API: ${IMPORT_URL}"

          echo "${{ steps.files.outputs.files }}" | while read -r f; do
            [[ -z "$f" ]] && continue
            echo "➡️  Importing $f"

            # Call Make Import API and capture HTTP code cleanly
            code=$(curl -sS --retry 3 --retry-delay 2 \
              -X POST "${IMPORT_URL}" \
              -H "Authorization: Token ${MAKE_API_TOKEN}" \
              -H "X-Team-Id: ${MAKE_TEAM_ID}" \
              -H "Content-Type: application/json" \
              --data-binary "@${f}" \
              -o resp.json -w "%{http_code}")

            if [[ "${code}" -ge 200 && "${code}" -lt 300 ]]; then
              echo "✅ Imported ${f} (HTTP ${code})"
              echo "IDs:"; jq -r '.items[]?.id // .id // empty' resp.json || true
            else
              echo "❌ Import failed for ${f} (HTTP ${code}) — response body (truncated):"
              head -c 2000 resp.json || true
              exit 1
            fi
          done

      - name: No changes to deploy
        if: steps.files.outputs.files == ''
        run: echo "No blueprint changes detected."
