name: Deploy Make blueprints

on:
  push:
    branches: [ main ]
    paths:
      - 'make/blueprints/**/*.json'
  workflow_dispatch: {}  # allows manual run from Actions

permissions:
  contents: read

jobs:
  import_blueprints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure jq is available
        run: sudo apt-get update && sudo apt-get install -y jq

      # Decide which blueprint files to send
      - name: Collect blueprint files
        id: files
        shell: bash
        run: |
          set -euo pipefail
          if [[ "${{ github.event_name }}" == "push" ]]; then
            # Only files changed in this commit (under make/blueprints/*.json)
            CHANGED=$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} \
              | grep -E '^make/blueprints/.*\.json$' || true)
          else
            # Manual run: deploy everything we find
            CHANGED=$(find make/blueprints -type f -name '*.json' 2>/dev/null || true)
          fi

          echo "files<<EOF" >> "$GITHUB_OUTPUT"
          echo "$CHANGED" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

          echo "Discovered files:"
          echo "$CHANGED"

      - name: Import blueprints to Make
        if: steps.files.outputs.files != ''
        env:
          MAKE_API_TOKEN: ${{ secrets.MAKE_API_TOKEN }}
          MAKE_TEAM_ID:   ${{ secrets.MAKE_TEAM_ID }}
          # Optional override (e.g., us1). If not set, default to EU since your org is eu2.
          MAKE_API_BASE:  ${{ secrets.MAKE_API_BASE }}
        shell: bash
        run: |
          set -euo pipefail

          # Default base URL to EU region when not explicitly set.
          API_BASE="${MAKE_API_BASE:-https://eu2.make.com/api/v2}"
          IMPORT_URL="${API_BASE%/}/blueprints/import"

          echo "Using Make API: $IMPORT_URL"

          if [[ -z "${MAKE_API_TOKEN:-}" || -z "${MAKE_TEAM_ID:-}" ]]; then
            echo "❌ Missing MAKE_API_TOKEN or MAKE_TEAM_ID secrets."
            exit 1
          fi

          echo "${{ steps.files.outputs.files }}" | while read -r f; do
            [[ -z "$f" ]] && continue
            echo "➡️  Importing $f"

            # POST blueprint JSON to Make Import API
            curl -sS --retry 3 --retry-delay 2 \
              -X POST "$IMPORT_URL" \
              -H "Authorization: Token ${MAKE_API_TOKEN}" \
              -H "X-Team-Id: ${MAKE_TEAM_ID}" \
              -H "Content-Type: application/json" \
              --data-binary "@$f" \
              -o resp.json -w "\nHTTP:%{http_code}\n"

            code=$(tail -n1 resp.json | sed 's/HTTP://')
            if [[ "$code" -ge 200 && "$code" -lt 300 ]]; then
              echo "✅ Imported $f (HTTP $code)"
              echo "IDs:"; jq -r '.items[]?.id // .id // empty' resp.json || true
            else
              echo "❌ Import failed for $f (HTTP $code)"
              head -c 2000 resp.json || true
              exit 1
            fi
          done

      - name: No changes to deploy
        if: steps.files.outputs.files == ''
        run: echo "No blueprint changes detected."
